# Generated by Django 4.2.23 on 2025-08-08 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ФИО')),
                ('worker', models.CharField(choices=[('монах', 'Монах'), ('священник', 'Священник'), ('прихожанин', 'Прихожанин')], max_length=100, verbose_name='Статус')),
                ('description', models.TextField(help_text='Можно использовать HTML-теги', verbose_name='Биография')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/photos/', verbose_name='Фотография')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['full_name'],
            },
        ),
    ]
