# Generated by Django 4.2.23 on 2025-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Год смерти'),
        ),
    ]
